//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTraining
    {
        public int ID_GroupTraining { get; set; }
        public string GroupTrainingTitle { get; set; }
        public int GroupTrainingTrainer_ID { get; set; }
        public string GroupTrainingDate { get; set; }
        public string GroupTrainingTime { get; set; }
        public int GroupTrainingMaxClients { get; set; }
        public int GroupTrainingRecordedClients { get; set; }
    
        public virtual Trainers Trainers { get; set; }
    }
}
