//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID_Payment { get; set; }
        public int PaymentClient_ID { get; set; }
        public string PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public int PaymentMethod_ID { get; set; }
        public string PaymentMembershipEndDate { get; set; }
        public string PaymentReceiptNumber { get; set; }
        public int PaymentSubscription_ID { get; set; }
        public Nullable<int> PaymentAdditionalService_ID { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
