//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriptions()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int ID_Subscription { get; set; }
        public int TypeSubscription_ID { get; set; }
        public decimal SubscriptionPrice { get; set; }
        public int SubscriptionAvailableServices_ID { get; set; }
        public Nullable<int> Discount { get; set; }
        public string SubscriptionPeriodExpired { get; set; }
        public int SubscriptionStatus_ID { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual SubscriptionStatuses SubscriptionStatuses { get; set; }
        public virtual TypeSubscription TypeSubscription { get; set; }
    }
}
