//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSchedules
    {
        public int ID_Schedule { get; set; }
        public int Trainer_ID { get; set; }
        public string WorkDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        public virtual Trainers Trainers { get; set; }
    }
}
